# Generated by Django 3.1.7 on 2021-02-23 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20210118_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='botype',
            new_name='bot_type',
        ),
        migrations.RenameField(
            model_name='bot',
            old_name='current_profit',
            new_name='profit',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='cursus',
            new_name='mode',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='thread',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='starttime',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='history',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='livestatus',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='longhistory',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='usdprofit',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='botname',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='user',
        ),
        migrations.AddField(
            model_name='bot',
            name='live_status',
            field=models.TextField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', null=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='thread',
            name='bot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bot.bot'),
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.TextField(choices=[('binance', 'binance'), ('poloniex', 'poloniex'), ('bitz', 'bitz'), ('ftx', 'ftx'), ('kraken', 'kraken'), ('bittrex', 'bittrex'), ('kucoin', 'kucoin'), ('digifinex', 'digifinex'), ('bw', 'bw'), ('huobipro', 'huobipro')], default='')),
                ('pair', models.TextField(choices=[('BTC/USDT', 'BTC-USDT'), ('ETH/USDT', 'ETH-USDT'), ('LINK/USDT', 'LINK-USDT'), ('XRP/USDT', 'XRP-USDT'), ('BCH/USDT', 'BCH-USDT'), ('XTZ/USDT', 'XTZ-USDT'), ('ETH/BTC', 'ETH-BTC'), ('LTC/USDT', 'LTC-USDT'), ('EOS/USDT', 'EOS-USDT'), ('DASH/USDT', 'DASH-USDT'), ('XLM/USDT', 'XLM-USDT'), ('SOL/BTC', 'SOL-BTC'), ('ZEC/USDT', 'ZEC-USDT'), ('XTZ/BTC', 'XTZ-BTC'), ('XMR/BTC', 'XMR-BTC'), ('TRX/USDT', 'TRX-USDT'), ('ADA/USDT', 'ADA-USDT'), ('XRP/BTC', 'XRP-BTC'), ('NEO/USDT', 'NEO-USDT'), ('LTC/BTC', 'LTC-BTC'), ('DASH/BTC', 'DASH-BTC'), ('EOS/BTC', 'EOS-BTC'), ('DATA/BTC', 'DATA-BTC'), ('ATOM/USDT', 'ATOM-USDT'), ('QTUM/USDT', 'QTUM-USDT'), ('ADA/BTC', 'ADA-BTC'), ('NAV/BTC', 'NAV-BTC'), ('ENJ/USDT', 'ENJ-USDT'), ('ALGO/USDT', 'ALGO-USDT'), ('IOTA/USDT', 'IOTA-USDT'), ('TRX/BTC', 'TRX-BTC'), ('LTO/BTC', 'LTO-BTC')], default='', max_length=10)),
                ('amount', models.FloatField(default=0.0)),
                ('entry_price', models.FloatField(default=0.0)),
                ('exit_price', models.FloatField(default=None)),
                ('fee', models.FloatField(default=0.0)),
                ('start_time', models.DateTimeField(default=None)),
                ('end_time', models.DateTimeField(default=None)),
                ('live_detail', models.TextField(default='[]')),
                ('status', models.TextField(choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE')], default='')),
                ('paper_trading', models.BooleanField(default=True)),
                ('bot', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
            ],
        ),
    ]
