# Generated by Django 3.1.7 on 2021-02-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20210223_0924'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderhistory',
            table='"bot_order_history"',
        ),
    ]
