# Generated by Django 3.1.7 on 2021-02-24 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20210223_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='live_status',
        ),
        migrations.AlterField(
            model_name='thread',
            name='bot',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='bot.bot'),
        ),
    ]
