# Generated by Django 3.1.7 on 2021-03-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20210301_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='exchange',
            field=models.CharField(choices=[('binance', 'binance'), ('poloniex', 'poloniex'), ('bitz', 'bitz'), ('ftx', 'ftx'), ('kraken', 'kraken'), ('bittrex', 'bittrex'), ('kucoin', 'kucoin'), ('digifinex', 'digifinex'), ('bw', 'bw'), ('huobipro', 'huobipro')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='pair',
            field=models.CharField(choices=[('BTC/USDT', 'BTC-USDT'), ('ETH/USDT', 'ETH-USDT'), ('LINK/USDT', 'LINK-USDT'), ('XRP/USDT', 'XRP-USDT'), ('BCH/USDT', 'BCH-USDT'), ('XTZ/USDT', 'XTZ-USDT'), ('ETH/BTC', 'ETH-BTC'), ('LTC/USDT', 'LTC-USDT'), ('EOS/USDT', 'EOS-USDT'), ('DASH/USDT', 'DASH-USDT'), ('XLM/USDT', 'XLM-USDT'), ('SOL/BTC', 'SOL-BTC'), ('ZEC/USDT', 'ZEC-USDT'), ('XTZ/BTC', 'XTZ-BTC'), ('XMR/BTC', 'XMR-BTC'), ('TRX/USDT', 'TRX-USDT'), ('ADA/USDT', 'ADA-USDT'), ('XRP/BTC', 'XRP-BTC'), ('NEO/USDT', 'NEO-USDT'), ('LTC/BTC', 'LTC-BTC'), ('DASH/BTC', 'DASH-BTC'), ('EOS/BTC', 'EOS-BTC'), ('DATA/BTC', 'DATA-BTC'), ('ATOM/USDT', 'ATOM-USDT'), ('QTUM/USDT', 'QTUM-USDT'), ('ADA/BTC', 'ADA-BTC'), ('NAV/BTC', 'NAV-BTC'), ('ENJ/USDT', 'ENJ-USDT'), ('ALGO/USDT', 'ALGO-USDT'), ('IOTA/USDT', 'IOTA-USDT'), ('TRX/BTC', 'TRX-BTC'), ('LTO/BTC', 'LTO-BTC')], default='', max_length=10),
        ),
    ]
