# Generated by Django 3.1.7 on 2021-03-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20210301_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='exit_price',
            field=models.FloatField(default=0.0),
        ),
    ]
