# Generated by Django 3.1.7 on 2021-03-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20210302_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='end_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='exit_price',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
