# Generated by Django 3.1.7 on 2021-04-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20210401_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='copy',
        ),
        migrations.AlterField(
            model_name='bot',
            name='root',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
