# Generated by Django 3.1.5 on 2021-01-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poloniex',
            name='balance',
            field=models.FloatField(null=True),
        ),
    ]
