# Generated by Django 3.1.5 on 2021-01-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_poloniex_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='binance',
            name='balance',
            field=models.FloatField(null=True),
        ),
    ]
