# Generated by Django 3.1.5 on 2021-01-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_binance_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binance',
            name='balance',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='poloniex',
            name='balance',
            field=models.TextField(null=True),
        ),
    ]
