# Generated by Django 3.1.5 on 2021-01-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210120_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binance',
            old_name='balance',
            new_name='fees',
        ),
        migrations.RenameField(
            model_name='poloniex',
            old_name='balance',
            new_name='fees',
        ),
    ]
